streaming/in.go

Always try to read full segment size and ignore "unexpected EOF".
If end of file the next read will be 0 bytes and an proper EOF will be delivered.

Ignore unexpected EOF

---

.github/workflows/lint.yml

golangci-lint has a new version, updating to that.

update golangci-lint version to v1.44

---

install.sh

The install script throws out an error when used on Macs with M1/M2 chips. The binaries seem to exist so adding darwin/arm64 to the list of obtainable binaries stops the installer from erroring out and correctly grabs and installs the binaries.

Added darwin/arm64 to get_binaries

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
go.sum
keys/keys.go
keys/keys_test.go
streaming/streaming_test.go

- deprecate golang versions 1.16 and 1.17 in github actions
- update golang-ci version in github action
- clean go.sum
- refactor code for deprecated `io/ioutil`

Refactor/update golang versions1.19

---

keys/keys.go

- simplify the way x25519 keys are generated by making use of `ecdh.X25519`

new way to generate x25519 keys

---

.github/workflows/release.yml
internal/version/version.go

goreleaser args were deprecated, keeping them up to date

fix args for goreleaser

---

internal/version/version.go
streaming/in.go
streaming/streaming_test.go

Unfortunately a large PR, apologies, even if I feel this is a simplification.
This PR adds opportunistic usage if the underlying data provider supports Seek, this allows for the main use case of reading small specific bits of large files. But this also allows for e.g. reading the end of a file first and then going back to an earlier position (if supported).
Interface changes are the addition of `Seek` and `Close` to permit `Seeker` and `Closer`. `GetHeader` has also changed from
`func (c Crypt4GHReader) GetHeader() []byte` to `func (c *Crypt4GHReader) GetHeader() []byte`.

Rewrite to add support for random-acces for Crypt4GHReader

---

internal/version/version.go
keys/keys.go
keys/keys_test.go

We used to panic on non-PEM-encoded keys, don't do that.
Also, some PEM-areas with less data than expected would also cause panics, fixes that as well.

Do not panic on unexpected key format

---

internal/version/version.go
streaming/in.go
streaming/streaming_test.go

This fixes a bug that could lead to incorrect data being returned in some cases.
When doing reads, we determine the largest amount of data we can read in a single swoop to check that area for holes caused by any edit lists. This is the lowest number of the length of the slice we should store data in and the readable data left in the buffer.
The computation incorrectly used the number of bytes that had been read rather than bytes that can be read, leading to the incorrect part of the logical decrypted stream being checked for holes.
Checking an area that is too large is not a problem, but if the area to check is too small, it could lead to incorrect data being returned if the smaller bit does not contain holes but the correctly calculated (based on the amount of bytes that can be read from …

Bugfix; incorrect length was used to check for discarded areas

---

internal/version/version.go
streaming/in.go
streaming/streaming_test.go

This fixes a bug where the position in the underlying data stream was not properly updated when seeking forward in a non-seekable stream, which could lead to incorrect data returned. A related possible issue with delayed update of stream position after read is also fixed.
This PR also makes almost all test run for both seekable and non-seekable data source streams.

Fix bug when seeking in a non-seekable source stream leading to boundary crossings.

---

streaming/streaming_test.go

This should hopefully succeed when #106 is merged.

Add some tests of EOF handling

---

README.md

**Description:**
This pull request updates the README file to provide enhanced installation instructions specifically for users with M1 Macs. Given the unique permission requirements of the M1 Mac architecture, particularly when writing to protected directories like `/usr/local/bin`, the existing instructions could lead to a 'Permission Denied' error during installation. The updated instructions offer clear guidance on how to successfully install the software on M1 Macs, ensuring a smoother setup process for users with this hardware.

Update `README` with enhanced installation instructions for `M1` Macs

---

README.md
internal/cli/cli.go
internal/version/version.go

- bump version to 1.9.0
- add `C4GH_PASSPHRASE` env var as an option for passing password to secret key
- update docs

add C4GH_PASSPHRASE  as an option

---

README.md

- instructions for macos and linux are the same.
- add reference for examples folder

join instructions for linux and macos

---

internal/version/version.go
keys/keys.go
keys/keys_test.go
streaming/streaming_test.go

This fixes support for unencrypted private crypt4gh keys. Support essentially existed but due to a logic error wasn't usable (KDF was checked against a list of actual KDFs, not including `none`, which is used for the unencrypted case) and failed if no match was found.
This moves the unencrypted case up a bit and lets the following code be a little simpler, also adds a testcase for an unencrypted key.

Add support for unencrypted private crypt4gh keys

---

model/headers/headers.go
model/headers/headers_test.go

Add straight-forward function, given a header/private key that can decrypt it, return the encrypted segment size used in the stream.

Add convenience function to return the size of an encrypted segment

---

internal/version/version.go
model/headers/headers.go
model/headers/headers_test.go
streaming/streaming_test.go

Allow passing of zero or more EncryptedHeaderPacket that will be added to the reencrypted header by ReEncryptHeader. If a packet of the same type exists already it will be replaced.

Add ability to add/replace headers when doing header re-encryption

---

internal/version/version.go
model/headers/headers.go
model/headers/headers_test.go

This adds some sanity limits when reading header packets without which one could possibly executedenial-of-service attacks through resource consumption.
I normally do not like libraries arbitrarily restricting otherewise valid usages, but think these limits are permissive enough that it should not be a problem. If it's still considered too restrictive, one can implement the ability to pass flags through varargs, meaning the signature used in calls could remain the same so no code would need to be rewritten unless they want to pass such flags). I currently can't think of any use case that would need that, though.

Add some sanity limits on header values

---

.github/workflows/lint.yml

When the language has no solution to check the overflow in time of convert, so linter shouldn't check the overflow.

[linter] Exclude `G115 - integer overflow`

---

.github/dependabot.yml

Group dependabot updates so we get a single PR and as such a single patch release going forward.

Group updates so we get a single release

---

kdf/kdf.go
kdf/kdf_test.go

I have been looking more deeply into the [Java version of Crypt4GH](https://github.com/ELIXIR-NO/FEGA-Norway/tree/main/lib/crypt4gh) created by Dmytro Titov (@dtitov) many years ago, 
and especially the [KDF functions](https://crypt4gh.readthedocs.io/en/latest/keys.html) that stretch the password used to encrypt the private key file.
I compared the Java version to the [Python implementation](https://github.com/EGA-archive/crypt4gh) and this [Go implementation](https://github.com/neicnordic/crypt4gh) to see if the KDFs produce the same hash values and verify that private key files created with the different versions are compatible with each other.
The good news is that all three versions produce the same hash for SCrypt, which is the preferred and default KDF. For the BCrypt alternative, …

Change PBKDF2 hash from SHA512 to SHA256 (according to specification)
